// Feature: package-categories, Property 24: The Emit_Script emits one COPY per discovered non-excluded manifest at both anchors
//
// The Emit_Script (`scripts/emit-effective-dockerfile.sh`) is dependency-free
// POSIX sh + awk, so it cannot be unit-tested in-process: its discovery IS the
// filesystem (four glob patterns plus a per-directory `package.json` existence
// test). This property therefore drives the REAL script as a child process
// against generated temp repository skeletons, which is why it lives in
// `packages/integration-tests/` rather than `packages/build-tools/tests/` even
// though the assertion is a property rather than an example.
//
// Each run:
//   1. generates a repository skeleton — the three Namespace_Containers each
//      independently absent / present-and-empty / present-with-members,
//      arbitrary top-level and member directory names (some dot-prefixed, some
//      holding no `package.json`, some holding a DIRECTORY named
//      `package.json`, some named after an Exclusion_List entry);
//   2. runs the script with the skeleton as cwd, and asserts the emitted
//      Manifest_Copy_Block equals an independently computed oracle — exactly one
//      `COPY` line per directory that directly holds a `package.json` file and is
//      not an excluded top-level entry, character-identical at both anchors, root
//      manifest first, then non-excluded top-level packages, then one group per
//      container in the fixed order microservices, common, spa, ascending byte
//      order within every group;
//   3. runs the script again over the unchanged skeleton and asserts
//      byte-identical output;
//   4. adds ONE new member directory holding a `package.json` under a chosen
//      container and runs a third time, asserting the new `COPY` line appears in
//      its sorted position with no edit to the script and no edit to the
//      template (R11.10).
//
// The skeleton gets a `scripts` symlink into the real repository so the script
// can be invoked exactly as documented — `sh scripts/emit-effective-dockerfile.sh`
// — with the skeleton as cwd. That also proves discovery is cwd-relative: the
// script never reaches back into the repository it lives in.
//
// The committed `Dockerfile.template` is copied into every skeleton, so the
// anchors and the ENTRYPOINT the script keys off are the real ones.
//
// NOT modelled: a `package.json` that exists but is unreadable. The script's
// guard is `[ -f ... ]` (existence of a regular file), so a present-but-mode-000
// manifest would still get a COPY line. Reproducing that in a test is not
// portable (a root-owned CI runner reads it anyway), so R11.1's "readable"
// clause is exercised only through the absent / not-a-regular-file cases.
//
// Validates: Requirements 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.10

import { spawnSync } from "node:child_process";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { afterAll, describe, expect, it } from "vitest";
import * as fc from "fast-check";

const __dirname = dirname(fileURLToPath(import.meta.url));
// tests/ -> integration-tests -> packages -> repo root
const repoRoot = resolve(__dirname, "..", "..", "..");
const realScriptsDir = resolve(repoRoot, "scripts");
const committedTemplate = readFileSync(
  resolve(repoRoot, "Dockerfile.template"),
  "utf8",
);

/** The three Namespace_Containers, in the fixed group order the block uses. */
const CONTAINERS = ["microservices", "common", "spa"] as const;
type Container = (typeof CONTAINERS)[number];

/** The four-entry Exclusion_List, matched against top-level names only (R11.3). */
const EXCLUDED_TOPLEVEL: readonly string[] = [
  "integration-tests",
  "microservices",
  "common",
  "spa",
];

const MANIFEST_HEADER =
  "# --- manifest COPY (generated by scripts/emit-effective-dockerfile.sh) ---";
const ROOT_COPY = "COPY package.json package-lock.json ./";

// ---------------------------------------------------------------------------
// Skeleton model
// ---------------------------------------------------------------------------

/**
 * What a candidate directory holds where the script looks for a manifest:
 *   "file"    a regular `package.json`  -> discovered
 *   "none"    nothing                   -> not discovered
 *   "dir"     a DIRECTORY named `package.json` -> not discovered (`-f` fails)
 */
type ManifestState = "file" | "none" | "dir";

/** A candidate directory. `name` already carries the leading dot when hidden. */
interface Dir {
  readonly name: string;
  readonly manifest: ManifestState;
}

interface ContainerSpec {
  /** false => the container directory does not exist at all. */
  readonly present: boolean;
  /** State of `packages/<container>/package.json` (the container's OWN manifest). */
  readonly ownManifest: ManifestState;
  readonly members: readonly Dir[];
}

interface Skeleton {
  /** Direct entries of `packages/`, none named after a Namespace_Container. */
  readonly topLevel: readonly Dir[];
  /** An optional top-level directory literally named `integration-tests`. */
  readonly integrationTests: Dir | null;
  readonly containers: Readonly<Record<Container, ContainerSpec>>;
  /** Container to receive the R11.10 late addition, and the name to add. */
  readonly addTo: Container;
  readonly addName: string;
}

// Uppercase letters are deliberately in the alphabet: byte order puts every
// uppercase letter before every lowercase one, whereas a locale-aware collation
// interleaves them. Without `LC_ALL=C` in the script, mixed-case sibling names
// are exactly what makes the ordering assertion fail.
const NAME_HEAD =
  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
const NAME_TAIL = `${NAME_HEAD}-`;

const bareNameArb: fc.Arbitrary<string> = fc
  .tuple(
    fc.constantFrom(...NAME_HEAD.split("")),
    fc.array(fc.constantFrom(...NAME_TAIL.split("")), {
      minLength: 0,
      maxLength: 4,
    }),
  )
  .map(([head, tail]) => head + tail.join(""));

const manifestStateArb: fc.Arbitrary<ManifestState> = fc.constantFrom(
  "file",
  "file",
  "none",
  "dir",
);

/**
 * A candidate directory. `hidden` prefixes a dot, which no glob in the script
 * matches, so such a directory must never contribute a COPY line however its
 * manifest looks.
 */
const dirArb: fc.Arbitrary<Dir> = fc
  .record({
    bare: bareNameArb,
    hidden: fc.boolean(),
    manifest: manifestStateArb,
  })
  .map(({ bare, hidden, manifest }) => ({
    name: hidden ? `.${bare}` : bare,
    manifest,
  }));

/**
 * Member names may also be one of the Exclusion_List entries: the exclusion is
 * top-level only, so `packages/common/spa/package.json` must still be COPYed.
 */
const memberArb: fc.Arbitrary<Dir> = fc.oneof(
  { weight: 3, arbitrary: dirArb },
  {
    weight: 1,
    arbitrary: fc.record({
      name: fc.constantFrom(...EXCLUDED_TOPLEVEL),
      manifest: manifestStateArb,
    }),
  },
);

// Case-insensitive uniqueness: macOS filesystems are case-insensitive by
// default, so `Ab` and `aB` would be the same directory there. Deduplicate on
// the lowercased name so a skeleton is reproducible on any host.
const dirKey = (d: Dir): string => d.name.toLowerCase();

const containerArb: fc.Arbitrary<ContainerSpec> = fc
  .record({
    present: fc.boolean(),
    ownManifest: manifestStateArb,
    members: fc.uniqueArray(memberArb, {
      selector: dirKey,
      minLength: 0,
      maxLength: 4,
    }),
  })
  .map((spec) =>
    spec.present
      ? spec
      : { ...spec, ownManifest: "none" as const, members: [] },
  );

const skeletonArb: fc.Arbitrary<Skeleton> = fc.record({
  topLevel: fc.uniqueArray(
    // Top-level names never collide with a Namespace_Container directory or
    // with `integration-tests`; those four are modelled explicitly.
    dirArb.filter((d) => !EXCLUDED_TOPLEVEL.includes(d.name.toLowerCase())),
    { selector: dirKey, minLength: 0, maxLength: 5 },
  ),
  integrationTests: fc.option(
    fc.record({
      name: fc.constant("integration-tests"),
      manifest: manifestStateArb,
    }),
    { nil: null },
  ),
  containers: fc.record({
    microservices: containerArb,
    common: containerArb,
    spa: containerArb,
  }),
  addTo: fc.constantFrom(...CONTAINERS),
  addName: bareNameArb,
});

// ---------------------------------------------------------------------------
// Oracle: the Manifest_Copy_Block the model implies
// ---------------------------------------------------------------------------

/** A directory is discovered iff a glob matches it AND it holds a manifest file. */
function discovered(d: Dir): boolean {
  return d.manifest === "file" && !d.name.startsWith(".");
}

/**
 * Ascending byte order. Every generated name is ASCII, for which JavaScript's
 * default UTF-16 code-unit ordering IS byte order — the same ordering
 * `LC_ALL=C` pins the shell's glob expansion to.
 */
function byByte(names: readonly string[]): string[] {
  return [...names].sort();
}

function copyLine(packageDir: string): string {
  return `COPY ${packageDir}/package.json ${packageDir}/`;
}

/** The expected block: root manifest, top level, then one group per container. */
function expectedBlock(s: Skeleton): string[] {
  const topLevelCandidates: Dir[] = [
    ...s.topLevel,
    ...(s.integrationTests ? [s.integrationTests] : []),
    ...CONTAINERS.filter((c) => s.containers[c].present).map((c) => ({
      name: c,
      manifest: s.containers[c].ownManifest,
    })),
  ];

  const topLevel = byByte(
    topLevelCandidates
      .filter(discovered)
      .map((d) => d.name)
      .filter((name) => !EXCLUDED_TOPLEVEL.includes(name)),
  ).map((name) => copyLine(`packages/${name}`));

  const groups = CONTAINERS.flatMap((c) =>
    byByte(s.containers[c].members.filter(discovered).map((d) => d.name)).map(
      (name) => copyLine(`packages/${c}/${name}`),
    ),
  );

  return [ROOT_COPY, ...topLevel, ...groups];
}

// ---------------------------------------------------------------------------
// Skeleton materialisation
// ---------------------------------------------------------------------------

function writeCandidate(parent: string, d: Dir): void {
  const dir = join(parent, d.name);
  mkdirSync(dir, { recursive: true });
  if (d.manifest === "file") {
    writeFileSync(join(dir, "package.json"), '{"private":true}\n', "utf8");
  } else if (d.manifest === "dir") {
    mkdirSync(join(dir, "package.json"), { recursive: true });
  }
}

/** Materialise a skeleton in a fresh temp directory and return its root. */
function materialise(baseDir: string, s: Skeleton): string {
  const root = mkdtempSync(join(baseDir, "skeleton-"));

  // Root manifests: the block's first COPY line names both unconditionally, so
  // they exist here for realism only.
  writeFileSync(join(root, "package.json"), '{"private":true}\n', "utf8");
  writeFileSync(join(root, "package-lock.json"), "{}\n", "utf8");
  writeFileSync(join(root, "Dockerfile.template"), committedTemplate, "utf8");
  // Invoke the REAL script, as documented, with the skeleton as cwd.
  symlinkSync(realScriptsDir, join(root, "scripts"), "dir");

  const packagesDir = join(root, "packages");
  mkdirSync(packagesDir, { recursive: true });

  for (const d of s.topLevel) writeCandidate(packagesDir, d);
  if (s.integrationTests) writeCandidate(packagesDir, s.integrationTests);

  for (const c of CONTAINERS) {
    const spec = s.containers[c];
    if (!spec.present) continue;
    const containerDir = join(packagesDir, c);
    writeCandidate(packagesDir, { name: c, manifest: spec.ownManifest });
    for (const member of spec.members) writeCandidate(containerDir, member);
  }

  return root;
}

// ---------------------------------------------------------------------------
// Running the script
// ---------------------------------------------------------------------------

interface EmitResult {
  readonly status: number;
  readonly stderr: string;
  readonly out: string;
}

function emit(root: string, selector: string): EmitResult {
  const env: Record<string, string> = {
    ...(process.env as Record<string, string>),
    DOCKERFILE: "Dockerfile.template",
    // Deliberately NOT the real artifact name: even a cwd mishap could not
    // clobber the repository's generated `Dockerfile`.
    EFFECTIVE_DOCKERFILE: "Dockerfile.generated",
    MICROSERVICES: selector,
  };
  // The default namespace (`packages/microservices`) is cwd-relative, so it
  // already points inside the skeleton; an inherited value must not override it.
  delete env.MICROSERVICE_NAMESPACE;

  const run = spawnSync("sh", ["scripts/emit-effective-dockerfile.sh"], {
    cwd: root,
    env,
    encoding: "utf8",
  });

  let out = "";
  try {
    out = readFileSync(join(root, "Dockerfile.generated"), "utf8");
  } catch {
    // A failing run writes nothing; the caller asserts on status/stderr.
  }

  return { status: run.status ?? -1, stderr: run.stderr ?? "", out };
}

/**
 * The Manifest_Copy_Block(s) in an emitted Dockerfile: each generated header
 * line plus the run of `COPY` lines immediately following it.
 */
function manifestBlocks(emitted: string): string[][] {
  const lines = emitted.split("\n");
  const blocks: string[][] = [];
  for (let i = 0; i < lines.length; i += 1) {
    if (lines[i] !== MANIFEST_HEADER) continue;
    const block: string[] = [];
    let j = i + 1;
    while (j < lines.length && lines[j].startsWith("COPY ")) {
      block.push(lines[j]);
      j += 1;
    }
    blocks.push(block);
  }
  return blocks;
}

function occurrences(haystack: string, needle: string): number {
  return haystack.split(needle).length - 1;
}

// ---------------------------------------------------------------------------
// The property
// ---------------------------------------------------------------------------

const workDir = mkdtempSync(join(tmpdir(), "emit-dockerfile-property-"));

afterAll(() => {
  rmSync(workDir, { recursive: true, force: true });
});

describe("Property 24: one COPY per discovered non-excluded manifest, at both anchors", () => {
  it("emits the oracle block at both anchors, deterministically, for any skeleton", () => {
    fc.assert(
      fc.property(skeletonArb, (skeleton) => {
        const root = materialise(workDir, skeleton);
        try {
          // An explicit, non-empty Selector keeps this property about manifest
          // DISCOVERY. `*` additionally requires the microservices container to
          // exist and to hold at least one member (otherwise the Selector
          // resolves to no microservices, which is R6 territory, not R11.5), so
          // it is only used when the skeleton can satisfy it.
          const microservicesResolvable =
            skeleton.containers.microservices.members.some(discovered);
          const selector = microservicesResolvable ? "*" : "svc-a,svc-b";

          const first = emit(root, selector);
          // R11.5: an absent or empty Namespace_Container contributes nothing
          // and the run still succeeds.
          expect(
            first.status,
            `exit ${first.status}; stderr: ${first.stderr}`,
          ).toBe(0);

          const expected = expectedBlock(skeleton);
          const blocks = manifestBlocks(first.out);

          // R11.2: one block per anchor, and the two are character-identical.
          expect(blocks).toHaveLength(2);
          expect(blocks[0].join("\n")).toBe(blocks[1].join("\n"));

          // R11.1/R11.3/R11.4/R11.5/R11.6: exact content AND exact order.
          expect(blocks[0]).toEqual(expected);

          // Exactly one COPY line per discovered manifest per anchor — nothing
          // duplicated inside a block, and nothing stray elsewhere in the file.
          for (const line of expected) {
            expect(occurrences(first.out, `\n${line}\n`)).toBe(2);
          }

          // R11.6: two consecutive runs over an unchanged tree are byte-identical.
          const second = emit(root, selector);
          expect(second.status).toBe(0);
          expect(second.out).toBe(first.out);

          // R11.10: a new container member holding a package.json is picked up
          // on the next run, with no edit to the script and none to the template.
          const container = skeleton.containers[skeleton.addTo];
          const taken = new Set(container.members.map(dirKey));
          let added = skeleton.addName;
          while (taken.has(added.toLowerCase())) added += "x";

          const containerDir = join(root, "packages", skeleton.addTo);
          if (!container.present) {
            mkdirSync(containerDir, { recursive: true });
          }
          writeCandidate(containerDir, { name: added, manifest: "file" });

          const grown: Skeleton = {
            ...skeleton,
            containers: {
              ...skeleton.containers,
              [skeleton.addTo]: {
                ...container,
                // Creating the member directory creates the container too.
                present: true,
                members: [
                  ...container.members,
                  { name: added, manifest: "file" },
                ],
              },
            },
          };

          const third = emit(root, selector);
          expect(
            third.status,
            `exit ${third.status}; stderr: ${third.stderr}`,
          ).toBe(0);
          const grownBlocks = manifestBlocks(third.out);
          expect(grownBlocks).toHaveLength(2);
          expect(grownBlocks[0].join("\n")).toBe(grownBlocks[1].join("\n"));
          expect(grownBlocks[0]).toEqual(expectedBlock(grown));
        } finally {
          rmSync(root, { recursive: true, force: true });
        }
      }),
      // House style, kept: numRuns: 200. Each run spawns THREE real `sh`
      // processes and materialises a temp tree, which is why the explicit
      // timeout below is generous — but the script is dependency-free sh + one
      // awk, so a run costs ~10 ms and the whole property lands around 8 s.
      // No deviation from the house numRuns was needed.
      { numRuns: 200 },
    );
  }, 300_000);
});
