// Task 12.2 — the Emit_Script reads its Discovery_Roots from the
// Project_Config_File (config-driven-discovery spec).
//
// Feature: config-driven-discovery, Requirement 11 (11.1, 11.3, 11.4, 11.5,
// 11.6, 11.9, 11.11).
//
// The Emit_Script (`scripts/emit-effective-dockerfile.sh`) no longer hard-codes
// `packages/microservices`, `packages/common`, `packages/spa`. It reads the
// three `roots` members from `scaffold.config.json` (directly inside the
// Project_Directory), defaulting each to its Root_Default when absent. This
// suite drives the REAL script against a NON-DEFAULT configuration and asserts:
//
//   * the Manifest_Copy_Block iterates the CONFIGURED roots — one COPY line per
//     member of `services/`, `libs/`, `web/` — at both anchors (R11.3);
//   * the top-level `packages/*` scan still contributes its non-excluded
//     members, because none of the configured roots' first path segments is
//     `packages` (R11.4);
//   * the derived Exclusion_List (first path segment of each configured root +
//     `integration-tests`) drops nothing under `packages/` except
//     `integration-tests`, so the four Framework_Singletons still get COPY lines
//     (R11.5);
//   * an empty configured common root contributes no COPY line and the run still
//     exits zero (R11.9);
//   * the ENV toggle lines name the members of the configured microservice root,
//     not the default `packages/microservices/*` (R11.6);
//   * the block is byte-identical at both anchors and ordered root-manifests →
//     top-level → microservice → common → spa, each group in byte order (R11.11).
//
// The generated Dockerfile carries NO scope value (R11.12 routes the scope to
// the container build as the `ARG WORKSPACE_SCOPE` build argument, which this
// script never touches), so this suite asserts nothing about a scope.
//
// --- This suite NEVER touches the real working tree -------------------------
// The non-default `scaffold.config.json` and the relocated root directories are
// written ONLY inside a `pristineWorktree()` copy — an OS temp directory that
// captures the working tree (uncommitted edits included) and runs `npm ci`
// there. NO `scaffold.config.json` is ever written into the checked-out
// repository: an untracked config file would change what every other suite's
// Emit_Script run reads. The copy's directory is passed as both the
// Project_Directory (the script reads `scaffold.config.json` relative to cwd)
// and the spawn cwd. Teardown removes the copy; there is nothing in the real
// tree to undo. This follows the pattern of `dev-error-recovery.test.ts` and
// `dev-session-scope.test.ts`.
//
// Validates: Requirements 11.1, 11.3, 11.4, 11.5, 11.6, 11.9, 11.11

import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { spawnSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pristineWorktree, type PristineWorktreeResult } from "./helpers.js";

const EMIT_SCRIPT = "scripts/emit-effective-dockerfile.sh";
const MANIFEST_HEADER =
  "# --- manifest COPY (generated by scripts/emit-effective-dockerfile.sh) ---";
const ROOT_COPY = "COPY package.json package-lock.json ./";

// The non-default roots this suite configures. None begins with `packages`, so
// the top-level `packages/*` scan is unaffected and every Framework_Singleton
// still gets its COPY line.
const MS_ROOT = "services";
const COMMON_ROOT = "libs";
const SPA_ROOT = "web";

// The relocated microservice members (byte order: alpha, beta) and one common
// member. The spa root (`web/`) is left EMPTY on purpose to exercise R11.9.
const MS_MEMBERS = ["alpha", "beta"] as const;
const COMMON_MEMBERS = ["shared"] as const;

// pristineWorktree() runs `npm ci` in a fresh temp tree; give it a generous
// budget. The emit runs themselves are milliseconds.
const PRISTINE_TIMEOUT_MS = 600_000;

let pristine: PristineWorktreeResult | undefined;
/** The emitted Dockerfile bytes for `MICROSERVICES=*`, captured once. */
let emitted: string | undefined;
let emitStatus = -1;
let emitStderr = "";

/** A minimal, valid workspace manifest for a synthesised member package. */
function memberManifest(scopedName: string): string {
  return (
    JSON.stringify(
      {
        name: scopedName,
        version: "0.0.0",
        private: true,
        type: "module",
      },
      null,
      2,
    ) + "\n"
  );
}

beforeAll(() => {
  pristine = pristineWorktree();
  if (pristine.available !== true) {
    return;
  }
  const dir = pristine.dir;

  // Re-root every path this suite writes at the pristine copy. Create the
  // relocated microservice and common members; leave the spa root absent to
  // exercise R11.9's "empty/absent root contributes no COPY line".
  for (const id of MS_MEMBERS) {
    const memberDir = resolve(dir, MS_ROOT, id);
    mkdirSync(memberDir, { recursive: true });
    writeFileSync(
      join(memberDir, "package.json"),
      memberManifest(`@microservices/${id}`),
    );
  }
  for (const name of COMMON_MEMBERS) {
    const memberDir = resolve(dir, COMMON_ROOT, name);
    mkdirSync(memberDir, { recursive: true });
    writeFileSync(
      join(memberDir, "package.json"),
      memberManifest(`@microservices/${name}`),
    );
  }

  // The non-default configuration, written INSIDE the copy only. It declares a
  // `scope` too, which the Emit_Script must ignore entirely (R11.12).
  writeFileSync(
    resolve(dir, "scaffold.config.json"),
    JSON.stringify(
      {
        scope: "@microservices",
        roots: {
          microservice: MS_ROOT,
          common: COMMON_ROOT,
          spa: SPA_ROOT,
        },
      },
      null,
      2,
    ) + "\n",
  );

  // Run the real script exactly as documented, with the copy as cwd, output
  // redirected to a temp path inside the copy so the copy's own gitignored
  // Dockerfile is what changes (never the real tree).
  const outPath = resolve(dir, "Dockerfile.generated");
  const env: Record<string, string> = {
    ...(process.env as Record<string, string>),
    EFFECTIVE_DOCKERFILE: outPath,
    MICROSERVICES: "*",
  };
  const run = spawnSync("sh", [EMIT_SCRIPT], {
    cwd: dir,
    env,
    encoding: "utf8",
  });
  emitStatus = run.status ?? -1;
  emitStderr = run.stderr ?? "";
  try {
    emitted = readFileSync(outPath, "utf8");
  } catch {
    emitted = undefined;
  }
}, PRISTINE_TIMEOUT_MS);

afterAll(() => {
  if (pristine?.available === true) {
    pristine.cleanup();
    pristine = undefined;
  }
});

/**
 * The Manifest_Copy_Block(s) in the emitted Dockerfile: each generated header
 * line plus the run of COPY lines immediately following it.
 */
function manifestBlocks(text: string): string[][] {
  const lines = text.split("\n");
  const blocks: string[][] = [];
  for (let i = 0; i < lines.length; i += 1) {
    if (lines[i] !== MANIFEST_HEADER) continue;
    const block: string[] = [];
    let j = i + 1;
    while (j < lines.length && lines[j].startsWith("COPY ")) {
      block.push(lines[j]);
      j += 1;
    }
    blocks.push(block);
  }
  return blocks;
}

/** The identifiers the script baked in, recovered from its ENV lines. */
function bakedIdentifiers(text: string): string[] {
  return [...text.matchAll(/^ENV MICROSERVICE_([A-Z0-9_]+)_ENABLED=enabled$/gm)]
    .map((match) => match[1].toLowerCase())
    .sort();
}

describe("emit-effective-dockerfile.sh reads Discovery_Roots from scaffold.config.json", () => {
  it("skips cleanly when the pristine worktree is unavailable", () => {
    if (pristine === undefined || pristine.available !== true) {
      console.warn(
        `SKIP emit-dockerfile-config: ${pristine?.reason ?? "pristine tree unavailable"}`,
      );
      return;
    }
    // Nothing to assert here; the real assertions run in the guarded cases
    // below. This case exists so the suite reports a passing test rather than
    // an empty run when the environment supports it.
    expect(pristine.available).toBe(true);
  });

  it(
    "iterates the configured roots at both anchors and leaves packages/* to the top-level scan (R11.3, R11.4, R11.5, R11.9, R11.11)",
    () => {
      if (pristine === undefined || pristine.available !== true) {
        return; // reason already reported by the skip case above
      }
      expect(emitStatus, `stderr: ${emitStderr}`).toBe(0);
      const text = emitted as string;

      const blocks = manifestBlocks(text);
      // R11.3: one block per anchor, byte-identical.
      expect(blocks).toHaveLength(2);
      expect(blocks[0].join("\n")).toBe(blocks[1].join("\n"));

      // The four Framework_Singletons are direct `packages/*` members and none
      // of the configured roots' first segments is `packages`, so each still
      // gets a top-level COPY line (R11.4, R11.5).
      const block = blocks[0];
      expect(block[0]).toBe(ROOT_COPY);
      for (const singleton of [
        "build-tools",
        "contracts",
        "overseer",
      ]) {
        expect(block).toContain(
          `COPY packages/${singleton}/package.json packages/${singleton}/`,
        );
      }

      // The configured microservice members are COPYed from `services/`, in
      // byte order, NOT from the default `packages/microservices/*` (R11.3).
      for (const id of MS_MEMBERS) {
        expect(block).toContain(
          `COPY ${MS_ROOT}/${id}/package.json ${MS_ROOT}/${id}/`,
        );
      }
      // No COPY line references the default microservice root. (The template's
      // prose still mentions `packages/microservices/`, so this is asserted
      // against the generated COPY lines only, not the whole document.)
      for (const line of block) {
        expect(line).not.toContain("packages/microservices/");
      }

      // The configured common member is COPYed from `libs/`, not the default
      // `packages/common/*`.
      for (const name of COMMON_MEMBERS) {
        expect(block).toContain(
          `COPY ${COMMON_ROOT}/${name}/package.json ${COMMON_ROOT}/${name}/`,
        );
      }

      // R11.9: the configured spa root (`web/`) holds no member, so it
      // contributes no COPY line and the run still exits zero.
      expect(text).not.toContain(`${SPA_ROOT}/`);

      // R11.11: the group order is root-manifest, then top-level `packages/*`,
      // then the microservice group, then the common group (spa is empty). The
      // two relocated microservice members appear consecutively and in byte
      // order, after every top-level `packages/` COPY line.
      const alphaIdx = block.indexOf(
        `COPY ${MS_ROOT}/alpha/package.json ${MS_ROOT}/alpha/`,
      );
      const betaIdx = block.indexOf(
        `COPY ${MS_ROOT}/beta/package.json ${MS_ROOT}/beta/`,
      );
      const sharedIdx = block.indexOf(
        `COPY ${COMMON_ROOT}/shared/package.json ${COMMON_ROOT}/shared/`,
      );
      expect(alphaIdx).toBeGreaterThan(0);
      expect(betaIdx).toBe(alphaIdx + 1);
      expect(sharedIdx).toBeGreaterThan(betaIdx);
      // Every top-level `packages/` COPY line precedes the microservice group.
      const lastPackagesIdx = block.reduce(
        (acc, line, idx) =>
          line.startsWith("COPY packages/") ? idx : acc,
        -1,
      );
      expect(lastPackagesIdx).toBeLessThan(alphaIdx);
    },
    PRISTINE_TIMEOUT_MS,
  );

  it(
    "bakes the configured microservice members as the toggle-default ENV lines (R11.6)",
    () => {
      if (pristine === undefined || pristine.available !== true) {
        return;
      }
      expect(emitStatus, `stderr: ${emitStderr}`).toBe(0);
      const text = emitted as string;

      // `*` resolves to every member of the CONFIGURED microservice root, so the
      // baked toggles name alpha and beta — never the default microservice1/2/3.
      expect(bakedIdentifiers(text)).toEqual([...MS_MEMBERS].sort());
      expect(text).not.toContain("MICROSERVICE_MICROSERVICE1_ENABLED");
    },
    PRISTINE_TIMEOUT_MS,
  );
});
