// Feature: package-categories — migration facts for the relocated Common_Package
// (design "Components and Interfaces / 11. packages/common/config/", "Migration
// shape").
//
// The sample shared library moved from its former top-level location under
// `packages/` into the `common` Namespace_Container at `packages/common/config`.
// This suite pins the observable facts of that move against the committed tree,
// at the source-of-truth level (the committed files themselves), so a
// regression in any of them is caught without running the build pipeline:
//
//   1. The relocated package holds its four constituents: `package.json`,
//      `tsconfig.json`, `src/`, and `tests/` (R8.1).
//   2. Its `tsconfig.json` `extends` `../../../tsconfig.base.json` — one level
//      deeper than before — and that relative path resolves to the
//      repository-root base config (R8.3).
//   3. The relocated manifest declares the SAME `name`, `type`, `main`,
//      `types`, and the four standard scripts the pre-relocation manifest did,
//      so it satisfies Common_Package validation with no manifest edit (R8.10).
//   4. Both consumers still declare `@microservices/config` (R8.6): the move is
//      invisible to a by-name importer.
//   5. No stale path remains: the Build_System sources, repo-level scripts,
//      `Dockerfile.template`, the Root_Manifest, and every test source contain
//      no textual reference to the former path, and that directory no longer
//      exists (R8.2, R8.4, R8.8).
//
// The stale-path scan matches the former path at a path boundary: the token
// followed by `/`, a quote, whitespace, or end-of-input. The relocated path
// `packages/common/config` does not contain the former path as a substring
// (after `packages/` comes `common`, not `config`), so it can never trip the
// check; the boundary anchor additionally excludes an unrelated name such as
// `packages/configuration`.
//
// This file deliberately never writes the former path as one contiguous
// literal — the forbidden token is assembled from `packages/` and `config`
// wherever it is needed — so the scan, which reads every test source in the
// repository (this one included), does not flag itself.
//
// ---------------------------------------------------------------------------
// Build-costing baseline comparisons (task 1.4).
// ---------------------------------------------------------------------------
//
// Beyond the relocation facts above, this suite also owns two of the
// Requirement 15 build-costing comparisons against the recorded Pre_Change_
// Baseline fixtures in `packages/integration-tests/baseline/` — the same
// example-based, exit-non-zero-and-name-the-difference shape task 1.3
// established for `baseline-equivalence.test.ts`:
//
//   6. Image_Tree staged entry sets (R15.5). For `*` and
//      `microservice1,microservice2` the sorted Project_Directory-relative
//      staged entry paths — `buildPlan(selector).stage[].targetDir` — equal the
//      recorded `image-tree.<selector>.json` fixture. This is the exact
//      observable `scripts/record-baseline.js` recorded, reached through the
//      same public entry point, so a threading change that perturbs the staged
//      set is caught here without assembling a real tree.
//
//   7. Generated `Dockerfile` bytes (R11.2). For `*`, unset, and
//      `microservice1,microservice2` the bytes the Emit_Script produces from
//      `Dockerfile.template` equal the recorded `dockerfile.<selector>`
//      fixture, byte for byte. The Emit_Script is spawned exactly as the
//      recorder spawned it (same input template, same `MICROSERVICES` env), but
//      its output is redirected to a temp path via `EFFECTIVE_DOCKERFILE`, so
//      the run leaves the checked-out tree — including the gitignored generated
//      `Dockerfile` — untouched. The generated bytes are a function of the
//      input template, the selector, and the discovered filesystem alone; the
//      output path never enters them, so redirecting it changes nothing that is
//      compared.
//
// Neither comparison mutates the working tree: `buildPlan` only reads manifests,
// and the Emit_Script writes solely to the temp path handed to it.
//
// Validates: Requirements 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.8, 8.10, 15.5, 11.2,
//   15.12, 15.13, 14.12

import { describe, it, expect, afterAll } from "vitest";
import { spawnSync } from "node:child_process";
import {
  existsSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  statSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";
import { dirname, join, relative, resolve } from "node:path";

import { buildPlan } from "@microservices/build-tools/dist/build-plan.js";
import { defaultEffectiveConfig } from "@microservices/build-tools/dist/project-config.js";
import { projectContext } from "@microservices/build-tools/dist/project-context.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
// tests/ -> integration-tests -> packages -> repo root
const repoRoot = resolve(__dirname, "..", "..", "..");

/** Where the recorded Pre_Change_Baseline fixtures live, repo-relative. */
const BASELINE_DIR = resolve(repoRoot, "packages/integration-tests/baseline");

/** The relocated Common_Package directory, repo-relative. */
const CONFIG_DIR = "packages/common/config";

/**
 * The retired pre-relocation directory, which must no longer exist. Assembled
 * from parts rather than written as one literal so this test file does not
 * itself contain the forbidden token the stale-path scan below rejects across
 * every test source (R8.8).
 */
const OLD_CONFIG_DIR = `packages/${"config"}`;

interface Manifest {
  readonly name?: string;
  readonly type?: string;
  readonly main?: string;
  readonly types?: string;
  readonly scripts?: Readonly<Record<string, string>>;
  readonly dependencies?: Readonly<Record<string, string>>;
}

function readManifest(relativePath: string): Manifest {
  return JSON.parse(
    readFileSync(resolve(repoRoot, relativePath), "utf8"),
  ) as Manifest;
}

function readText(relativePath: string): string {
  return readFileSync(resolve(repoRoot, relativePath), "utf8");
}

describe("the relocated package holds its four constituents (R8.1)", () => {
  it("has package.json, tsconfig.json, src/, and tests/", () => {
    expect(existsSync(resolve(repoRoot, CONFIG_DIR, "package.json"))).toBe(true);
    expect(existsSync(resolve(repoRoot, CONFIG_DIR, "tsconfig.json"))).toBe(
      true,
    );

    const src = resolve(repoRoot, CONFIG_DIR, "src");
    const tests = resolve(repoRoot, CONFIG_DIR, "tests");
    expect(existsSync(src) && statSync(src).isDirectory()).toBe(true);
    expect(existsSync(tests) && statSync(tests).isDirectory()).toBe(true);
  });
});

describe("the relocated tsconfig extends the repo-root base config (R8.3)", () => {
  const tsconfig = JSON.parse(readText(`${CONFIG_DIR}/tsconfig.json`)) as {
    readonly extends?: string;
  };

  it("extends ../../../tsconfig.base.json — one level deeper for the extra depth", () => {
    expect(tsconfig.extends).toBe("../../../tsconfig.base.json");
  });

  it("resolves to the repository-root tsconfig.base.json", () => {
    const resolved = resolve(repoRoot, CONFIG_DIR, tsconfig.extends ?? "");
    expect(resolved).toBe(resolve(repoRoot, "tsconfig.base.json"));
    expect(existsSync(resolved)).toBe(true);
  });
});

describe("the relocated manifest declares the same fields as before (R8.10)", () => {
  const manifest = readManifest(`${CONFIG_DIR}/package.json`);

  it("declares the same name, unchanged by the relocation (R8.5)", () => {
    expect(manifest.name).toBe("@microservices/config");
  });

  it("declares type: module", () => {
    expect(manifest.type).toBe("module");
  });

  it("declares main and types pointing at compiled output", () => {
    expect(manifest.main).toBe("./dist/index.js");
    expect(manifest.types).toBe("./dist/index.d.ts");
  });

  it("declares exactly the four standard scripts", () => {
    const scripts = manifest.scripts ?? {};
    for (const name of ["build", "test", "lint", "typecheck"] as const) {
      expect(scripts, `missing script '${name}'`).toHaveProperty(name);
      expect(typeof scripts[name]).toBe("string");
      expect((scripts[name] ?? "").length).toBeGreaterThan(0);
    }
  });
});

describe("microservice2 still declares @microservices/config directly (R8.6)", () => {
  // Only microservice2 declares `@microservices/config` in its own manifest.
  // Microservice3 no longer names the Config_Package directly: it now depends
  // on `@microservices/extended-config` and reaches `@microservices/config`
  // transitively through it (design "Migration shape" / worked staged sets:
  // `ms3 → extended-config → config`). The by-name importer test therefore
  // narrows to `microservice2` alone — asserting a direct `@microservices/config`
  // dependency on `microservice3` would contradict that new dependency chain.
  it.each(["microservice2"] as const)(
    "%s depends on @microservices/config by package name",
    (id) => {
      const deps =
        readManifest(`packages/microservices/${id}/package.json`)
          .dependencies ?? {};
      expect(deps).toHaveProperty("@microservices/config");
    },
  );
});

// ---------------------------------------------------------------------------
// Stale-path scan (R8.2, R8.4, R8.8).
// ---------------------------------------------------------------------------

/**
 * A path-boundary matcher for the former directory path, built from a fragment
 * so this source never contains the forbidden token contiguously. It matches
 * the token when followed by `/`, a quote, whitespace, a backslash, or the end
 * of input — so the bare directory, a path under it, and a quoted reference all
 * count, while a longer name such as the `configuration` variant does not.
 */
const STALE_PATH = new RegExp(`packages/${"config"}(?=$|[/"'\\s\\\\])`);

/** Whether `text` references the former directory path at a path boundary. */
function referencesStalePath(text: string): boolean {
  return STALE_PATH.test(text);
}

/** Directory names never descended into while collecting scannable sources. */
const IGNORED_DIRS = new Set(["node_modules", "dist", ".git"]);

/**
 * Every file under `dir` (recursively) whose name matches `keep`, repo-relative.
 * `node_modules`, `dist`, and any `.git*` entry are pruned so the scan sees
 * committed source only.
 */
function collectFiles(
  dir: string,
  keep: (fileName: string) => boolean,
): string[] {
  if (!existsSync(dir)) {
    return [];
  }
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name.startsWith(".git")) {
      continue;
    }
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      if (IGNORED_DIRS.has(entry.name)) {
        continue;
      }
      out.push(...collectFiles(full, keep));
    } else if (entry.isFile() && keep(entry.name)) {
      out.push(relative(repoRoot, full));
    }
  }
  return out;
}

/**
 * The full set of files R8.2/R8.4/R8.8 forbid a stale reference in:
 *   - every Build_System source under `packages/build-tools/src/`
 *   - every repo-level script under `scripts/`
 *   - `Dockerfile.template`
 *   - the Root_Manifest (`package.json`)
 *   - every test source in the repository (`*.test.ts` / `*.test-d.ts`),
 *     across all packages, per R8.8 ("no test in the repository")
 */
function scannedFiles(): string[] {
  const buildToolsSrc = collectFiles(
    resolve(repoRoot, "packages/build-tools/src"),
    () => true,
  );
  const scripts = collectFiles(resolve(repoRoot, "scripts"), () => true);
  const testSources = collectFiles(resolve(repoRoot, "packages"), (name) =>
    /\.test(-d)?\.ts$/.test(name),
  );

  return [
    ...buildToolsSrc,
    ...scripts,
    "Dockerfile.template",
    "package.json",
    ...testSources,
  ];
}

describe("no stale reference to the former path survives the move (R8.2, R8.4, R8.8)", () => {
  it("the former directory is absent", () => {
    expect(existsSync(resolve(repoRoot, OLD_CONFIG_DIR))).toBe(false);
  });

  it("no scanned source references the former path", () => {
    const offenders = scannedFiles().filter((file) =>
      referencesStalePath(readText(file)),
    );

    expect(
      offenders,
      `stale reference to the former sample-library path in:\n${offenders.join("\n")}`,
    ).toEqual([]);
  });

  it("the Root_Manifest lists packages/common/* and no former entry (R8.4)", () => {
    const workspaces =
      (readManifest("package.json") as { workspaces?: readonly string[] })
        .workspaces ?? [];
    expect(workspaces).toContain("packages/common/*");
    expect(workspaces).not.toContain(OLD_CONFIG_DIR);
    expect(workspaces).not.toContain(`${OLD_CONFIG_DIR}/*`);
  });
});

// ---------------------------------------------------------------------------
// 6. Image_Tree staged entry set equivalence (R15.5).
//
// Entry point: `buildPlan(selector)` from the compiled build-plan module — the
// exact function `scripts/record-baseline.js` recorded through. The observable
// is the sorted set of `plan.stage[].targetDir`, the Project_Directory-relative
// paths the assembler copies into the Image_Tree. `buildPlan` reads
// `process.env.MICROSERVICES` when given no argument and discovers packages
// relative to cwd, so each case pins cwd to the repo root and sets the Selector
// env for the call, restoring both afterward. It performs no filesystem write,
// so the working tree is left exactly as found.
// ---------------------------------------------------------------------------

/**
 * The Selectors the Image_Tree observable is recorded for, and the filename
 * slug each takes (task 1.1): `*` -> `all`, the two-service list ->
 * `microservice1-microservice2`.
 */
const IMAGE_TREE_SELECTORS: ReadonlyArray<{
  readonly slug: string;
  readonly value: string;
}> = [
  { slug: "all", value: "*" },
  {
    slug: "microservice1-microservice2",
    value: "microservice1,microservice2",
  },
];

/** Read a recorded baseline fixture as parsed JSON. */
function readBaselineJson(name: string): unknown {
  return JSON.parse(readFileSync(resolve(BASELINE_DIR, name), "utf8"));
}

/**
 * The sorted staged entry paths `buildPlan` produces for `selector`, reached
 * exactly as the recorder reached them. cwd is pinned to the repo root and the
 * Selector env is set for the duration of the call, both restored in `finally`
 * so one case never leaks into the next.
 */
function stagedEntriesFor(selector: string): string[] {
  const previousSelector = process.env.MICROSERVICES;
  const previousCwd = process.cwd();
  try {
    process.chdir(repoRoot);
    process.env.MICROSERVICES = selector;
    const plan = buildPlan(projectContext(defaultEffectiveConfig()), selector);
    return [...plan.stage.map((staged) => staged.targetDir)].sort();
  } finally {
    process.chdir(previousCwd);
    if (previousSelector === undefined) {
      delete process.env.MICROSERVICES;
    } else {
      process.env.MICROSERVICES = previousSelector;
    }
  }
}

describe("Image_Tree staged entry sets match the recorded baseline (R15.5)", () => {
  it.each(IMAGE_TREE_SELECTORS)(
    "selector $value stages exactly the recorded entry set",
    ({ slug, value }) => {
      const recorded = readBaselineJson(`image-tree.${slug}.json`);
      const observed = stagedEntriesFor(value);

      // Name the observable, the recorded value, and the observed value in the
      // failure message; a mismatch throws, so the run exits non-zero (1.3
      // failure shape).
      expect(
        observed,
        `Image_Tree staged entry set for selector "${value}" ` +
          `diverged from baseline/image-tree.${slug}.json.\n` +
          `  recorded: ${JSON.stringify(recorded)}\n` +
          `  observed: ${JSON.stringify(observed)}`,
      ).toEqual(recorded);
    },
  );
});

// ---------------------------------------------------------------------------
// 7. Generated Dockerfile byte equivalence (R11.2).
//
// The Emit_Script is spawned exactly as `scripts/record-baseline.js` spawned it
// — `sh scripts/emit-effective-dockerfile.sh` with MICROSERVICES set (or unset)
// and cwd at the repo root, reading the committed `Dockerfile.template`. The
// one difference is that the output is redirected to a temp file through
// `EFFECTIVE_DOCKERFILE`, so the gitignored generated `Dockerfile` in the
// working tree is never touched. The output path does not enter the generated
// bytes, so this redirection changes nothing that is compared, and the tree is
// left unmodified (the sanctioned no-mutation pattern the sibling
// `effective-dockerfile.test.ts` already uses).
// ---------------------------------------------------------------------------

/** The Emit_Script, repo-relative, invoked the way the documented build does. */
const EMIT_SCRIPT = "scripts/emit-effective-dockerfile.sh";

/**
 * The Selectors the Dockerfile observable is recorded for and their filename
 * slugs (task 1.1): `*` -> `all`, unset -> `blank`, the two-service list ->
 * `microservice1-microservice2`. `value: undefined` means "leave MICROSERVICES
 * unset", which the Selector resolves the same way as blank.
 */
const DOCKERFILE_SELECTORS: ReadonlyArray<{
  readonly slug: string;
  readonly value: string | undefined;
}> = [
  { slug: "all", value: "*" },
  { slug: "blank", value: undefined },
  {
    slug: "microservice1-microservice2",
    value: "microservice1,microservice2",
  },
];

/** A per-suite temp directory the emit output is redirected into. */
const dockerfileWorkDir = mkdtempSync(join(tmpdir(), "migration-dockerfile-"));
let dockerfileCounter = 0;

afterAll(() => {
  rmSync(dockerfileWorkDir, { recursive: true, force: true });
});

/**
 * Spawn the Emit_Script for `selector` (MICROSERVICES unset when `undefined`),
 * redirecting its output to a fresh temp path so the real generated Dockerfile
 * is never written. Returns the exit status and the emitted bytes.
 */
function emitDockerfile(selector: string | undefined): {
  readonly status: number;
  readonly stderr: string;
  readonly bytes: string;
} {
  dockerfileCounter += 1;
  const outPath = join(dockerfileWorkDir, `Dockerfile.${dockerfileCounter}`);

  const env: Record<string, string> = {
    ...(process.env as Record<string, string>),
    EFFECTIVE_DOCKERFILE: outPath,
  };
  delete env.MICROSERVICES;
  if (selector !== undefined) {
    env.MICROSERVICES = selector;
  }

  const run = spawnSync("sh", [EMIT_SCRIPT], {
    cwd: repoRoot,
    env,
    encoding: "utf8",
  });

  let bytes = "";
  try {
    bytes = readFileSync(outPath, "utf8");
  } catch {
    // A failing run writes nothing; the status/stderr assertion covers it.
  }

  return { status: run.status ?? -1, stderr: run.stderr ?? "", bytes };
}

describe("generated Dockerfile bytes match the recorded baseline (R11.2)", () => {
  it.each(DOCKERFILE_SELECTORS)(
    "selector $value emits the recorded Dockerfile bytes",
    ({ slug, value }) => {
      const recorded = readFileSync(
        resolve(BASELINE_DIR, `dockerfile.${slug}`),
        "utf8",
      );
      const { status, stderr, bytes } = emitDockerfile(value);

      // The emit run must succeed before a byte comparison is meaningful.
      expect(status, `emit-effective-dockerfile.sh stderr: ${stderr}`).toBe(0);

      // Name the observable and both sides on divergence; a mismatch throws, so
      // the run exits non-zero (1.3 failure shape).
      expect(
        bytes,
        `generated Dockerfile bytes for selector ` +
          `"${value === undefined ? "<unset>" : value}" diverged from ` +
          `baseline/dockerfile.${slug}.`,
      ).toBe(recorded);
    },
  );
});
