// This module writes the Microservice_Registry file that the Overseer imports.
//
// Step 3 of the build pipeline. It runs from the `generate-registry` bin —
// invoked by `npm start`, `npm run dev`, and the Dockerfile build stage — and
// from `buildImageTree` (image-tree.ts). Paths are relative to cwd, the repo
// root on every one of those entries, and errors propagate: Node prints them and
// exits non-zero. (R5.1–R5.5, R6.1, R6.2, R10.2, R10.4)

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { discoverPackages, type Discovery } from "./discovery.js";
import { OVERSEER } from "./framework.js";
import { resolveSelected } from "./selector.js";

/** The Overseer imports the generated registry from this path (R10.4, R10.5). */
const OUTPUT_PATH = `${OVERSEER.packageDir}/src/generated/microservice-registry.ts`;

/**
 * This function writes the registry for the selected microservices.
 *
 * It runs after discovery, so a Consumer_Package with an unreadable manifest
 * fails there and no registry is written at all (R3.4). Each entry's
 * `identifier` and import specifier come from the directory name, not from the
 * name the microservice's own manifest declares (R14.2). Module contents go
 * unchecked: a directory that is not a usable microservice module fails later,
 * at `tsc` build time, on the generated static import.
 *
 * @param selector the raw MICROSERVICES value; `undefined` means all.
 * @param discovery injectable so a caller that has already discovered walks the
 *   filesystem once.
 */
export function generateRegistry(
  selector = process.env.MICROSERVICES,
  discovery: Discovery = discoverPackages(),
): void {
  const identifiers = resolveSelected(
    selector,
    discovery.byCategory.microservice.map((pkg) => pkg.dirName),
  );

  const code = `// AUTO-GENERATED by @microservices/build-tools. Do not edit.
// Selector: ${selector ?? "*"}
${identifiers.map((id, i) => `import * as m${i} from "@microservices/${id}";`).join("\n")}
import type { MicroserviceRegistry } from "@microservices/contracts";

// COUPLING NOTE: the empty template at
// packages/overseer/src/generated/microservice-registry.template.ts must match
// this file's export name, type import, and shape. Keep them in sync; the
// typechecker is the safety net.
export const microserviceRegistry: MicroserviceRegistry = [
${identifiers.map((id, i) => `  { identifier: "${id}", module: m${i}, sourcePackage: "@microservices/${id}" },`).join("\n")}
];
`;

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, code, "utf8");
}
