// This module writes the Microservice_Registry file that the Overseer imports.
//
// Step 3 of the build pipeline. Its domain function `generateRegistry` runs from
// `runImageTreeCli` (image-tree.ts) and from `runGenerateRegistryCli` below —
// the latter invoked by the `generate-registry` bin, which `npm start`,
// `npm run dev`, and the Dockerfile build stage spawn. Paths are relative to
// cwd, the repo root on every one of those entries, and errors propagate: Node
// prints them and exits non-zero. (R5.1–R5.5, R6.1, R6.2, R10.2, R10.4, R8.1–R8.3)

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { requireProjectContext } from "./config-loader.js";
import { discoverPackages, type Discovery } from "./discovery.js";
import { OVERSEER } from "./framework.js";
import { type ProjectContext } from "./project-context.js";
import { resolveSelected } from "./selector.js";

/** The Overseer imports the generated registry from this path (R10.4, R10.5).
 *  A path literal, not a scope literal: `OVERSEER.packageDir` is scope-free. */
const OUTPUT_PATH = `${OVERSEER.packageDir}/src/generated/microservice-registry.ts`;

/**
 * This function writes the registry for the selected microservices.
 *
 * It runs after discovery, so a Consumer_Package with an unreadable manifest
 * fails there and no registry is written at all (R3.4). Each entry's
 * `identifier` and import specifier come from the directory name, not from the
 * name the microservice's own manifest declares (R14.2). Module contents go
 * unchecked: a directory that is not a usable microservice module fails later,
 * at `tsc` build time, on the generated static import.
 *
 * Every scoped name it emits — each microservice import specifier and
 * `sourcePackage`, the `contracts` type-import specifier, and the banner's
 * generator attribution — is composed from `context.scopedName(...)`, so the
 * registry carries the run's Configured_Scope and this module holds no scope
 * literal (R8.1–R8.3). For the default configuration the output is byte-identical
 * to the Pre_Change_Baseline (R8.5, R15.10).
 *
 * `resolveSelected` throws `[selector:empty]` when an all-selection finds no
 * candidate microservice (an existing-but-empty microservice root) and
 * `[selector:unmatched]` for a named identifier that matches none, so a Selector
 * resolving to zero microservices fails before the write and nothing is written
 * (R8.6, R8.7, R8.8).
 *
 * @param context the per-run derivation of this run's Effective_Config (R1.9).
 * @param selector the raw MICROSERVICES value; `undefined` means all.
 * @param discovery injectable so a caller that has already discovered walks the
 *   filesystem once.
 */
export function generateRegistry(
  context: ProjectContext,
  selector = process.env.MICROSERVICES,
  discovery: Discovery = discoverPackages(context),
): void {
  const identifiers = resolveSelected(
    selector,
    discovery.byCategory.microservice.map((pkg) => pkg.dirName),
  );

  const contractsSpecifier = context.scopedName("contracts");
  const specifierOf = (id: string): string => context.scopedName(id);

  const code = `// AUTO-GENERATED by ${context.scopedName("build-tools")}. Do not edit.
// Selector: ${selector ?? "*"}
${identifiers.map((id, i) => `import * as m${i} from "${specifierOf(id)}";`).join("\n")}
import type { MicroserviceRegistry } from "${contractsSpecifier}";

// COUPLING NOTE: the empty template at
// packages/overseer/src/generated/microservice-registry.template.ts must match
// this file's export name, type import, and shape. Keep them in sync; the
// typechecker is the safety net.
export const microserviceRegistry: MicroserviceRegistry = [
${identifiers.map((id, i) => `  { identifier: "${id}", module: m${i}, sourcePackage: "${specifierOf(id)}" },`).join("\n")}
];
`;

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, code, "utf8");
}

/**
 * The CLI adapter of the registry generator, invoked from
 * `bin/generate-registry.ts`.
 *
 * It holds the one effect the domain function does not: the config load, through
 * {@link requireProjectContext}, the one place a Config_Diagnostic reaches stderr
 * and the process exits over one (R1.10). On success it derives the context and
 * generates the registry for `process.env.MICROSERVICES`.
 */
export function runGenerateRegistryCli(): void {
  const context = requireProjectContext(); // R1.10
  generateRegistry(context, process.env.MICROSERVICES);
}
