// This module writes the Microservice_Registry file that the Entry_Module — the
// consumer's own entrypoint — statically imports.
//
// Step 3 of the build pipeline. Its domain function `generateRegistry` runs from
// `runImageTreeCli` (image-tree.ts) and from `runGenerateRegistryCli` below —
// the latter invoked by the `generate-registry` bin, which `npm start`,
// `npm run dev`, the Entry_Package's own `build`/`typecheck` scripts, and the
// Dockerfile build stage spawn. Paths are relative to cwd, the Project_Directory
// on every one of those entries, and errors propagate: Node prints them and
// exits non-zero. (R5.1–R5.5, R6.1, R6.2, R10.2, R10.4, R8.1–R8.3;
// registry-inversion R4.1–R4.10, R5.8)
//
// The registry is written into the CONSUMER's tree, under the Entry_Root taken
// from the threaded ProjectContext. This module therefore composes no
// Framework_Singleton path at all, which is what makes "writes no file under any
// Framework_Singleton's directory" a property of the module graph rather than a
// claim about a code path (registry-inversion R4.1).

import { mkdirSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { requireProjectContext } from "./config-loader.js";
import { discoverPackages, type Discovery } from "./discovery.js";
import { type ProjectContext } from "./project-context.js";
import { resolveSelected } from "./selector.js";

/**
 * The Generated_Registry's path for this run: `<Entry_Root>/src/generated/
 * microservice-registry.ts` (registry-inversion R4.1).
 *
 * The single derivation of that path: every writer, every presence guard, and
 * every test reads it from here, so a registry one path writes is the file every
 * other path compiles (registry-inversion R5.8). A path derivation, not a scope
 * derivation — `context.entryRoot` is scope-free.
 *
 * @param context the per-run derivation of this run's Effective_Config (R1.9).
 */
export function generatedRegistryPath(context: ProjectContext): string {
  return `${context.entryRoot}/src/generated/microservice-registry.ts`;
}

/**
 * The pure composer of the Generated_Registry's text — the whole emitted module,
 * given the run's context, the Selector it ran for, and the already-resolved
 * Selected_Microservices in their resolved order.
 *
 * Pure and total: it reads no filesystem, no environment, and no clock, so the
 * text is a function of its three arguments alone. That is the mechanism behind
 * determinism (registry-inversion R4.7) — two runs over the same ProjectContext,
 * Selector, and discovered packages cannot differ, because there is no other
 * input to differ over. The header carries no timestamp, no absolute path, no
 * host name, and no user name, and names no Registry_Template (R4.6).
 *
 * Every scoped name it emits — each microservice import specifier and
 * `sourcePackage`, the `contracts` type-import specifier, and the header's
 * generator attribution — is composed from `context.scopedName(...)`, so the
 * registry carries the run's Configured_Scope and this module holds no scope
 * literal (registry-inversion R4.5).
 *
 * Encoding discipline lives here: the text is assembled from template literals
 * containing `\n` only, and ends in exactly one `\n` (registry-inversion R4.10).
 * No `\r\n` anywhere, which is what keeps the emitted bytes host-independent.
 *
 * @param context the per-run derivation of this run's Effective_Config.
 * @param selector the raw MICROSERVICES value; `undefined` means all.
 * @param selected the Selected_Microservices' identifiers, in resolved order.
 */
export function registryText(
  context: ProjectContext,
  selector: string | undefined,
  selected: readonly string[],
): string {
  const contractsSpecifier = context.scopedName("contracts");
  const specifierOf = (id: string): string => context.scopedName(id);

  return `// AUTO-GENERATED by ${context.scopedName("build-tools")}. Do not edit.
// Selector: ${selector ?? "*"}
${selected.map((id, i) => `import * as m${i} from "${specifierOf(id)}";`).join("\n")}
import type { MicroserviceRegistry } from "${contractsSpecifier}";

export const microserviceRegistry: MicroserviceRegistry = [
${selected.map((id, i) => `  { identifier: "${id}", module: m${i}, sourcePackage: "${specifierOf(id)}" },`).join("\n")}
];
`;
}

/** Distinguishes the temporary files of two generations in one process. */
let writeCounter = 0;

/**
 * This function writes the registry for the selected microservices to
 * {@link generatedRegistryPath}, under the consumer's Entry_Root.
 *
 * It runs after discovery, so a Consumer_Package with an unreadable manifest
 * fails there and no registry is written at all (R3.4). Each entry's
 * `identifier` and import specifier come from the directory name, not from the
 * name the microservice's own manifest declares (R14.2; registry-inversion
 * R4.3). Module contents go unchecked: a directory that is not a usable
 * microservice module fails later, at `tsc` build time, on the generated static
 * import.
 *
 * `resolveSelected` throws `[selector:empty]` when an all-selection finds no
 * candidate microservice (an existing-but-empty microservice root) and
 * `[selector:unmatched]` for a named identifier that matches none. It runs
 * before the first `mkdirSync`, so a Selector resolving to zero microservices
 * creates no directory of the registry's path, writes no registry, and leaves an
 * already-present registry's bytes untouched (R8.6–R8.8; registry-inversion
 * R4.8).
 *
 * The write is whole-file and observably atomic: the complete text goes to a
 * sibling temporary file in the destination's own directory, which is then
 * renamed over the destination (registry-inversion R4.2). A plain write over an
 * existing file truncates first, so a concurrent `tsc --build` — and the dev
 * session runs one — could read a half-written module; the rename replaces the
 * destination's bytes wholesale in one operation instead, and keeping the
 * temporary file in the same directory keeps that rename on one filesystem. A
 * failure during the write leaves the previous complete bytes in place: the
 * temporary file is removed before the error propagates.
 *
 * @param context the per-run derivation of this run's Effective_Config (R1.9).
 * @param selector the raw MICROSERVICES value; `undefined` means all.
 * @param discovery injectable so a caller that has already discovered walks the
 *   filesystem once.
 */
export function generateRegistry(
  context: ProjectContext,
  selector = process.env.MICROSERVICES,
  discovery: Discovery = discoverPackages(context),
): void {
  // Before any directory is created and any byte is written (R4.8).
  const identifiers = resolveSelected(
    selector,
    discovery.byCategory.microservice.map((pkg) => pkg.dirName),
  );

  const code = registryText(context, selector, identifiers);

  const outputPath = generatedRegistryPath(context);
  mkdirSync(dirname(outputPath), { recursive: true });

  // Same-directory temporary sibling, so the rename is one atomic operation on
  // one filesystem rather than a cross-device copy. The pid and the per-process
  // counter keep two concurrent generators from sharing a temporary name.
  const tempPath = `${outputPath}.${process.pid}.${++writeCounter}.tmp`;
  try {
    writeFileSync(tempPath, code, "utf8");
    renameSync(tempPath, outputPath);
  } catch (error) {
    // Never leave a stray temporary file behind, and never a damaged registry:
    // the destination still holds its previous complete contents (R4.2).
    rmSync(tempPath, { force: true });
    throw error;
  }
}

/**
 * The CLI adapter of the registry generator, invoked from
 * `bin/generate-registry.ts`.
 *
 * It holds the one effect the domain function does not: the config load, through
 * {@link requireProjectContext}, the one place a Config_Diagnostic reaches stderr
 * and the process exits over one (R1.10). On success it derives the context and
 * generates the registry for `process.env.MICROSERVICES`.
 */
export function runGenerateRegistryCli(): void {
  const context = requireProjectContext(); // R1.10
  generateRegistry(context, process.env.MICROSERVICES);
}
