// AUTO-GENERATED by @microservices/build-tools. Do not edit.
// Selector: *
import * as m0 from "@microservices/microservice1";
import * as m1 from "@microservices/microservice2";
import * as m2 from "@microservices/microservice3";
import type { MicroserviceRegistry } from "@microservices/contracts";

export const microserviceRegistry: MicroserviceRegistry = [
  { identifier: "microservice1", module: m0, sourcePackage: "@microservices/microservice1" },
  { identifier: "microservice2", module: m1, sourcePackage: "@microservices/microservice2" },
  { identifier: "microservice3", module: m2, sourcePackage: "@microservices/microservice3" },
];
