#!/bin/sh
# Emit Dockerfile.effective: the repo-root Dockerfile plus the R6.6 per-service
# default-toggle ENV lines for the current MICROSERVICES selector.
#
# Dependency-free POSIX sh + awk on purpose: CI (and a fresh clone) can produce
# the effective Dockerfile without installing Node or running npm ci first.
#
# Selector handling is deliberately minimal:
#   *, empty, or whitespace-only -> every directory under packages/microservices
#   otherwise                    -> the comma-separated entries, whitespace trimmed
#
# It does NOT validate that the resulting identifiers exist, and it does NOT
# handle exotic selector spellings (`,,,`, duplicates, ...). That is not a gap:
# `generate-registry` running INSIDE the container is the authority on selector
# validity and fails the build with `[selector:unmatched]` for a bogus
# identifier. This script only decides which toggle defaults to bake in; a
# selector this script mis-reads can at worst bake a harmless extra ENV line
# into a build that the container-side generator then rejects anyway.
#
# Usage: MICROSERVICES=microservice1,microservice2 sh scripts/emit-effective-dockerfile.sh

set -eu

DOCKERFILE="${DOCKERFILE:-Dockerfile}"
EFFECTIVE="${EFFECTIVE_DOCKERFILE:-Dockerfile.effective}"
NAMESPACE="${MICROSERVICE_NAMESPACE:-packages/microservices}"

selector="${MICROSERVICES:-*}"

if [ ! -f "$DOCKERFILE" ]; then
  echo "[emit-effective-dockerfile] no such Dockerfile: $DOCKERFILE" >&2
  exit 1
fi

# The injection anchors on the LAST ENTRYPOINT instruction, which is the runtime
# stage's. ENV placed just before it still applies to the running container, and
# a deploy-time `-e` still overrides it.
anchor=$(awk '/^[[:space:]]*ENTRYPOINT([[:space:]]|\[)/ { line = NR } END { print line + 0 }' "$DOCKERFILE")
if [ "$anchor" -eq 0 ]; then
  echo "[emit-effective-dockerfile] $DOCKERFILE has no ENTRYPOINT instruction to anchor the toggle-default ENV injection" >&2
  exit 1
fi

# Resolve the selector to a newline-separated identifier list.
trimmed=$(printf '%s' "$selector" | tr -d '[:space:]')
if [ -z "$trimmed" ] || [ "$trimmed" = "*" ]; then
  if [ ! -d "$NAMESPACE" ]; then
    echo "[emit-effective-dockerfile] no such Microservice_Namespace: $NAMESPACE" >&2
    exit 1
  fi
  identifiers=$(ls -1 "$NAMESPACE" | sort)
else
  identifiers=$(printf '%s' "$selector" | tr ',' '\n' | sed 's/^[[:space:]]*//; s/[[:space:]]*$//' | grep -v '^$' || true)
fi

if [ -z "$identifiers" ]; then
  echo "[emit-effective-dockerfile] selector '$selector' resolved to no microservices" >&2
  exit 1
fi

# Build the block to inject: a header naming the selector, then one ENV per id.
# It travels to awk through the environment rather than `-v`, because a `-v`
# assignment cannot carry embedded newlines.
INJECT_BLOCK=$(printf '# --- R6.6 toggle defaults (generated by scripts/emit-effective-dockerfile.sh; selector: %s) ---' "$selector")
for identifier in $identifiers; do
  upper=$(printf '%s' "$identifier" | tr '[:lower:]' '[:upper:]')
  INJECT_BLOCK=$(printf '%s\nENV MICROSERVICE_%s_ENABLED=enabled' "$INJECT_BLOCK" "$upper")
done
export INJECT_BLOCK

{
  printf '# AUTO-GENERATED from %s by scripts/emit-effective-dockerfile.sh. Do not edit.\n' "$DOCKERFILE"
  printf '# Selector: %s\n' "$selector"
  awk -v anchor="$anchor" '
    NR == anchor { print ENVIRON["INJECT_BLOCK"] }
    { print }
  ' "$DOCKERFILE"
} >"$EFFECTIVE"

echo "[emit-effective-dockerfile] wrote $EFFECTIVE for selector '$selector'"
