#!/bin/sh
# rename-scope.sh — rename the npm scope used by every workspace package.
#
# The scope (default "@scaffold") is a placeholder: it appears in package
# names, dependency keys, import statements, the registry generator's emitted
# template, test fixtures, and comments. It is NOT the product name. When you
# adopt this scaffold for a real product, run this once to rebrand the scope:
#
#     sh scripts/rename-scope.sh @your-product
#
# then run `npm install` so the workspace symlinks re-resolve under the new
# scope and package-lock.json is regenerated.
#
# Usage:
#     sh scripts/rename-scope.sh <new-scope> [old-scope]
#
#   <new-scope>  Required. The new scope, with or without a leading "@"
#                (e.g. "@microservices" or "microservices").
#   [old-scope]  Optional. The current scope to replace (default "@scaffold").
#
# What it touches: tracked source, config, and test files that contain the
# literal token "<old-scope>/". What it deliberately does NOT touch:
#   - package-lock.json         (regenerated by `npm install`)
#   - the generated Dockerfile / Dockerfile.effective, and the generated
#     registry (all gitignored build output — they regenerate)
#   - node_modules/, dist/, .git/, *.tsbuildinfo
#   - the bare word "scaffold" anywhere (repo folder name, image tags): only
#     the "<old-scope>/" token is rewritten, so nothing else is collateral.
#
# POSIX sh, no dependencies beyond git + sed.
set -eu

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
  echo "usage: sh scripts/rename-scope.sh <new-scope> [old-scope]" >&2
  exit 2
fi

# Normalise both scopes to a leading "@".
normalise() {
  case "$1" in
    @*) printf '%s' "$1" ;;
    *)  printf '@%s' "$1" ;;
  esac
}

new_scope=$(normalise "$1")
old_scope=$(normalise "${2:-@scaffold}")

if [ "$new_scope" = "$old_scope" ]; then
  echo "new scope and old scope are identical ($new_scope); nothing to do." >&2
  exit 0
fi

# Basic sanity: an npm scope is "@" + lowercase alphanumerics and hyphens.
case "$new_scope" in
  @*[!a-z0-9-]*|@) echo "invalid scope: $new_scope (use @lowercase-with-hyphens)" >&2; exit 2 ;;
esac

# Move to the repo root regardless of where the script was invoked from.
cd "$(dirname "$0")/.."

# The token we rewrite always includes the trailing "/", so "@scaffold/x"
# changes but a bare "scaffold" (folder name, image tag) never does.
old_token="${old_scope}/"
new_token="${new_scope}/"

# Enumerate tracked files that contain the token, skipping generated output
# and the lockfile. git ls-files keeps us inside version control and honours
# .gitignore automatically (so the generated registry/Dockerfile are excluded).
files=$(git ls-files -z \
  | grep -zZv -e '^package-lock\.json$' \
               -e '/microservice-registry\.ts$' \
               -e '^Dockerfile$' \
               -e '^Dockerfile\.effective$' \
  | { grep -lzZ -- "$old_token" 2>/dev/null || true; } \
  | xargs -0 grep -lZ -- "$old_token" 2>/dev/null || true)

# The pipeline above is defensive across grep variants; fall back to a simple
# tracked-file scan if it produced nothing usable.
if [ -z "${files}" ]; then
  files=$(git ls-files \
    | grep -v -e '^package-lock\.json$' \
              -e '/microservice-registry\.ts$' \
              -e '^Dockerfile$' \
              -e '^Dockerfile\.effective$' \
    | while IFS= read -r f; do
        if grep -q -- "$old_token" "$f" 2>/dev/null; then printf '%s\n' "$f"; fi
      done)
fi

if [ -z "${files}" ]; then
  echo "no files contain the token '${old_token}'; nothing to rename."
  exit 0
fi

# Escape sed metacharacters in the tokens (only "/" and "&" matter here since
# scopes are alphanumeric + hyphen; "@" and "-" are literal in a BRE).
esc() { printf '%s' "$1" | sed 's/[&/\]/\\&/g'; }
old_esc=$(esc "$old_token")
new_esc=$(esc "$new_token")

count=0
printf '%s\n' "$files" | while IFS= read -r f; do
  [ -n "$f" ] || continue
  sed -i.bak "s/${old_esc}/${new_esc}/g" "$f"
  rm -f "$f.bak"
  echo "  rewrote $f"
  count=$((count + 1))
done

echo
echo "Renamed scope '${old_scope}' -> '${new_scope}'."
echo "Next: run 'npm install' to re-resolve workspaces and regenerate package-lock.json."
