#!/bin/sh
# rename-scope.sh — rename the npm scope used by every workspace package.
#
# The scope (default "@microservices") is a placeholder: it appears in package
# names, dependency keys, import statements, the registry generator's emitted
# template, test fixtures, and comments. It is NOT the product name. When you
# adopt this scaffold for a real product, run this once to rebrand the scope:
#
#     sh scripts/rename-scope.sh @your-product
#
# then run `npm install` so the workspace symlinks re-resolve under the new
# scope and package-lock.json is regenerated.
#
# Usage:
#     sh scripts/rename-scope.sh <new-scope> [old-scope]
#
#   <new-scope>  Required. The new scope, with or without a leading "@"
#                (e.g. "@microservices" or "microservices").
#   [old-scope]  Optional. The current scope to replace (default "@microservices").
#
# What it touches: tracked source, config, and test files that contain the
# old scope as a whole token — "@old-scope" followed by "/", punctuation, or
# end-of-line (so both "@old-scope/pkg" imports and a bare "@old-scope" scope
# directory reference are caught, but "@old-scopex" is left alone). What it
# deliberately does NOT touch:
#   - package-lock.json         (regenerated by `npm install`)
#   - the generated Dockerfile / Dockerfile.effective, and the generated
#     registry (all gitignored build output — they regenerate)
#   - node_modules/, dist/, .git/, *.tsbuildinfo
#   - this script itself: its "@microservices" mentions are the documented
#     default old-scope, not a usage, so rewriting them would break the
#     "default old-scope = current scope" invariant for the next run.
#   - the bare word "scaffold" anywhere (repo folder name, image tags): the
#     match requires the leading "@", so an unscoped word is never collateral.
#
# POSIX sh, no dependencies beyond git + sed.
set -eu

if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
  echo "usage: sh scripts/rename-scope.sh <new-scope> [old-scope]" >&2
  exit 2
fi

# Normalise both scopes to a leading "@".
normalise() {
  case "$1" in
    @*) printf '%s' "$1" ;;
    *)  printf '@%s' "$1" ;;
  esac
}

new_scope=$(normalise "$1")
old_scope=$(normalise "${2:-@microservices}")

if [ "$new_scope" = "$old_scope" ]; then
  echo "new scope and old scope are identical ($new_scope); nothing to do." >&2
  exit 0
fi

# Basic sanity: an npm scope is "@" + lowercase alphanumerics and hyphens.
case "$new_scope" in
  @*[!a-z0-9-]*|@) echo "invalid scope: $new_scope (use @lowercase-with-hyphens)" >&2; exit 2 ;;
esac

# Move to the repo root regardless of where the script was invoked from.
cd "$(dirname "$0")/.."

# Escape sed metacharacters. Scopes are "@" + [a-z0-9-], so only "&", "/" and
# "\" could bite; escaping them keeps the value literal in a BRE / replacement.
esc() { printf '%s' "$1" | sed 's/[&/\]/\\&/g'; }
old_esc=$(esc "$old_scope")
new_esc=$(esc "$new_scope")

# Match the old scope as a WHOLE token: "@old-scope" followed by a boundary —
# a non-identifier char (captured and preserved) or end-of-line. This catches
# both "@old/pkg" imports and a bare "@old" scope-directory reference, while
# leaving "@oldx" untouched. The leading "@" means an unscoped word is never
# matched, so the repo folder name and image tags are safe.
sed_script="s/${old_esc}\\([^A-Za-z0-9-]\\)/${new_esc}\\1/g; s/${old_esc}\$/${new_esc}/g"

# A grep pattern for the same boundary, to select the files worth rewriting.
grep_pattern="${old_scope}\\([^A-Za-z0-9-]\\|\$\\)"

# Enumerate tracked files, skipping the lockfile and generated build output.
# git ls-files stays inside version control and honours .gitignore (so the
# generated registry and Dockerfile are already excluded).
count=0
git ls-files \
  | grep -v -e '^package-lock\.json$' \
            -e '/microservice-registry\.ts$' \
            -e '^Dockerfile$' \
            -e '^Dockerfile\.effective$' \
            -e '^scripts/rename-scope\.sh$' \
  | while IFS= read -r f; do
      grep -Eq -- "$grep_pattern" "$f" 2>/dev/null || continue
      sed -i.bak "$sed_script" "$f"
      rm -f "$f.bak"
      echo "  rewrote $f"
      count=$((count + 1))
    done

echo
echo "Renamed scope '${old_scope}' -> '${new_scope}'."
echo "Next: run 'npm install' to re-resolve workspaces and regenerate package-lock.json."
