// Unit tests for the Registry_Generator's two new exported surfaces: the single
// output-path derivation `generatedRegistryPath(context)` and the pure text
// composer `registryText(context, selector, selected)`.
//
// Both are pure, so these tests need no tree and no cwd change. The one test
// that writes exercises the temporary-file-plus-rename discipline, and it writes
// only inside an OS temporary directory it removes afterwards — nothing in the
// checked-out repository is touched.
//
// Validates: Requirements 4.1, 4.2, 4.6, 4.10, 5.8

import {
  existsSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { afterEach, describe, expect, it } from "vitest";

import {
  generateRegistry,
  generatedRegistryPath,
  registryText,
} from "../src/generate-registry.js";
import type { ConsumerPackage, Discovery } from "../src/discovery.js";
import { defaultEffectiveConfig } from "../src/project-config.js";
import { projectContext } from "../src/project-context.js";

/** A Discovery whose microservice category holds one package per identifier;
 *  `generateRegistry` reads that field only. */
function discoveryOf(identifiers: readonly string[]): Discovery {
  const microservice: ConsumerPackage[] = identifiers.map((dirName) => ({
    category: "microservice",
    dirName,
    packageDir: `packages/microservices/${dirName}`,
    name: `@microservices/${dirName}`,
    dependencySpecifiers: [],
    buildKind: "tsc-project",
  }));
  return {
    byCategory: { microservice, common: [], spa: [] },
    nameByDir: new Map(),
    byName: new Map(),
  };
}

describe("generatedRegistryPath", () => {
  it("resolves under the Entry_Root, not under any Framework_Singleton (R4.1)", () => {
    const context = projectContext(defaultEffectiveConfig());
    expect(generatedRegistryPath(context)).toBe(
      "app/src/generated/microservice-registry.ts",
    );
    expect(generatedRegistryPath(context)).not.toContain("packages/");
  });

  it("follows a relocated Entry_Root", () => {
    const context = projectContext({
      ...defaultEffectiveConfig(),
      entry: "deploy/entry",
    });
    expect(generatedRegistryPath(context)).toBe(
      "deploy/entry/src/generated/microservice-registry.ts",
    );
  });
});

describe("registryText", () => {
  const context = projectContext(defaultEffectiveConfig());

  it("emits the two-line header, no Registry_Template reference, and no varying value (R4.6)", () => {
    const text = registryText(context, "*", ["microservice1"]);
    const lines = text.split("\n");
    expect(lines[0]).toBe(
      "// AUTO-GENERATED by @microservices/build-tools. Do not edit.",
    );
    expect(lines[1]).toBe("// Selector: *");
    expect(text).not.toContain("COUPLING NOTE");
    expect(text).not.toContain("template");
    expect(text).not.toContain(tmpdir());
  });

  it("names the selector it ran for, and `*` for an undefined selector", () => {
    expect(registryText(context, "a,b", ["a", "b"])).toContain(
      "// Selector: a,b",
    );
    expect(registryText(context, undefined, ["a"])).toContain("// Selector: *");
  });

  it("keeps the emitted shape one import and one entry per Selected_Microservice", () => {
    const text = registryText(context, "*", ["alpha", "beta"]);
    expect(text).toContain('import * as m0 from "@microservices/alpha";');
    expect(text).toContain('import * as m1 from "@microservices/beta";');
    expect(text).toContain(
      '  { identifier: "alpha", module: m0, sourcePackage: "@microservices/alpha" },',
    );
    expect(text).toContain(
      '  { identifier: "beta", module: m1, sourcePackage: "@microservices/beta" },',
    );
    expect(text).toContain(
      'import type { MicroserviceRegistry } from "@microservices/contracts";',
    );
    expect(text).toContain(
      "export const microserviceRegistry: MicroserviceRegistry = [",
    );
  });

  it("uses `\\n` only and ends in exactly one `\\n` (R4.10)", () => {
    const text = registryText(context, "*", ["alpha", "beta"]);
    expect(text).not.toContain("\r");
    expect(text.startsWith("\uFEFF")).toBe(false);
    expect(text.endsWith("\n")).toBe(true);
    expect(text.endsWith("\n\n")).toBe(false);
  });

  it("is deterministic over the same inputs (R4.7)", () => {
    expect(registryText(context, "*", ["alpha"])).toBe(
      registryText(context, "*", ["alpha"]),
    );
  });
});

describe("generateRegistry's write", () => {
  let tempRoot: string | undefined;
  let previousCwd: string | undefined;

  afterEach(() => {
    if (previousCwd !== undefined) process.chdir(previousCwd);
    if (tempRoot !== undefined)
      rmSync(tempRoot, { recursive: true, force: true });
    previousCwd = undefined;
    tempRoot = undefined;
  });

  function inTempTree(): string {
    tempRoot = mkdtempSync(join(tmpdir(), "registry-output-"));
    previousCwd = process.cwd();
    process.chdir(tempRoot);
    return tempRoot;
  }

  it("creates every absent directory of the path and leaves no temporary file (R4.2)", () => {
    const root = inTempTree();
    const context = projectContext(defaultEffectiveConfig());

    generateRegistry(context, "*", discoveryOf(["alpha"]));

    const outputPath = join(root, generatedRegistryPath(context));
    expect(existsSync(outputPath)).toBe(true);
    expect(readFileSync(outputPath, "utf8")).toBe(
      registryText(context, "*", ["alpha"]),
    );
    // Only the registry itself is left in the directory the generator created.
    expect(readdirSync(join(root, "app/src/generated"))).toEqual([
      "microservice-registry.ts",
    ]);
  });

  it("replaces an already-present registry's whole contents", () => {
    const root = inTempTree();
    const context = projectContext(defaultEffectiveConfig());

    generateRegistry(context, "*", discoveryOf(["alpha", "beta"]));
    generateRegistry(context, "alpha", discoveryOf(["alpha", "beta"]));

    const outputPath = join(root, generatedRegistryPath(context));
    expect(readFileSync(outputPath, "utf8")).toBe(
      registryText(context, "alpha", ["alpha"]),
    );
  });

  it("writes nothing and creates no directory when the Selector matches nothing (R4.8)", () => {
    const root = inTempTree();
    const context = projectContext(defaultEffectiveConfig());

    expect(() =>
      generateRegistry(context, "nosuch", discoveryOf(["alpha"])),
    ).toThrow(/\[selector:unmatched\]/);
    expect(existsSync(join(root, "app"))).toBe(false);

    expect(() => generateRegistry(context, "*", discoveryOf([]))).toThrow(
      /\[selector:empty\]/,
    );
    expect(existsSync(join(root, "app"))).toBe(false);
  });

  it("leaves an already-present registry's bytes alone on a failing run (R4.8)", () => {
    const root = inTempTree();
    const context = projectContext(defaultEffectiveConfig());
    const outputPath = join(root, generatedRegistryPath(context));

    generateRegistry(context, "*", discoveryOf(["alpha"]));
    const before = readFileSync(outputPath, "utf8");

    expect(() =>
      generateRegistry(context, "nosuch", discoveryOf(["alpha"])),
    ).toThrow(/\[selector:unmatched\]/);

    expect(readFileSync(outputPath, "utf8")).toBe(before);
  });
});
